

update-all:
    cd blog && just update
    cd dita-docs && just update

serve-all: update-all
   cd _build && php -S localhost:8080

publish-all: update-all
    rsync -Pav --delete -e "ssh -i /home/mzan/.ssh/guix-deploy" _build/ root@scratch.dokmelody.org:/var/www/scratch.dokmelody.org/ --chown=nginx:nginx
